---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: centos-7
    driver:
      box: centos/7
    run_list:
    - recipe[selinux::disabled]
  - name: ubuntu-16.04
    driver:
      box: bento/ubuntu-16.04
  - name: ubuntu-18.04
    driver:
      box: bento/ubuntu-18.04
  - name: debian-9
    driver:
      box: debian/stretch64


suites:
  - name: default
    run_list:
      - recipe[corosync::default]
    attributes:
