name 'corosync'
maintainer 'Petr Belyaev'
maintainer_email 'upcfrost@gmail.com'
license 'GPLv3.0'
description 'Installs/Configures Corosync'
long_description 'Installs/Configures Corosync'
version '0.1.0'
