name 'corosync'
maintainer 'Petr Belyaev'
maintainer_email 'upcfrost@gmail.com'
license 'all_rights'
description 'Installs/Configures Corosync'
long_description 'Installs/Configures Corosync'
version '0.1.0'
